name:                postkrypt
version:             0.1.0.0
github:              "radrow/postkrypt"
license:             BSD3
author:              "Radosław Rowicki"
maintainer:          "radrowicki@gmail.com"
copyright:           "2019 Radosław Rowicki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/radrow/postkrypt#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- mtl
- QuickCheck

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wextra

executables:
  postkrypt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wextra
    dependencies:
    - postkrypt

tests:
  postkrypt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postkrypt
